name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make log checker executable
        run: chmod +x log_checker.sh

      - name: Run log checker (fail on ERROR)
        run: |
          FAIL_ON_ERROR=1 ./log_checker.sh example.log

      - name: Build Docker image
        run: docker build -t devsecops-env-info .

      - name: Run Docker container
        run: docker run --rm -e APP_ENV=ci devsecops-env-info
